language: rust
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install libsystemd-dev pkg-config
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly